@localurl = http://localhost:7071/api/SampleBlobOutputFunction
@remoteurl = <Put in your remote URL>

### Send local request
POST {{localurl}}
Content-Type: application/json

{
  "id": "{{$guid}}",
  "nickName": "Hulk",
  "email":"bruce.banner@avengers.com",
  "location": {
      "region": "massachusetts",
      "country": "usa"
  }
}


### Send real request
POST {{remoteurl}}
Content-Type: application/json

{
  "id": "{{$guid}}",
  "nickName": "Hulk",
  "email":"bruce.banner@avengers.com",
  "location": {
      "region": "massachusetts",
      "country": "usa"
  }
}